PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS vector (
    id INTEGER PRIMARY KEY,
    vec BLOB NOT NULL,
    doc TEXT
);

CREATE TABLE IF NOT EXISTS simhash (
  id INTEGER PRIMARY KEY,
  vec_id INTEGER NOT NULL UNIQUE REFERENCES vector(id),
  hash BLOB NOT NULL
);
