name: "Publish Python Package"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test-build:
    name: "uv build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "install python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: "install uv"
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b
        with:
          version: "0.8.14"
          activate-environment: true

      - name: "uv sync and test"
        run: uv sync --locked --all-extras && uv run -m unittest

      - name: "build release distributions"
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - test-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
